global:
  scrape_interval: 5s # local is okay but since we dont have enough memory on azure vms you have to make it 30s at minimum

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"] # 0.0.0.0 instead of localhost to avoid problems with Docker