version: 2.1
# YAML anchor to avoid duplicates
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: bashikr/microblog
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  test:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run:
          name: install dependencies
          command: docker-compose up test

  build:
    executor: docker-publisher
    steps:
      - checkout # It's basically a git clone of code
      - setup_remote_docker # Creates a remote Docker environment configured to execute Docker commands.
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest -f docker/Dockerfile_prod .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      # Persists image.tar from the upper run on the workflow workspace
      # Special step used to persist a temporary file to be used by another job in the workflow.
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

