---
# Here you can add variables that will be available for all hosts.
region: northeurope
resource_group: DIDA-BAAA19-DV1617-H21-LP2 # Change me
domain_name: microblogonsteroids.software # Change me

root_user: azureuser

vmtags:
    StudentId: "baaa19" # Change me


pub_ssh_key_location: '/home/bashar/.ssh/id_rsa.pub' # Change me, your local ssh key!